### ISSUE TITLE
Script turns some pictures blank

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [catalyst/moodle-tool_encoded#23]
Hi Catalyst,

Moodle version: 4.2.6+
Plugin version: 2024021900 

I have a site with a lot of base-64 encoded images in mod_label activities and i tried your plugin. I generated the report of mod label and found around 2500 instances and then run the convertion adhoc task. Everything seems to work as intended. The adhoc log said everything was success and the report as well. I had a specific course to just double check and somehow the convertion was done - but no image was displayed. I tried to generate a new report, but there was no base-64 encoded label.

So my issue is that the convertion has happened but some images is not shown other is. What to do?

Below ive attached pictures of the raw html of and converted base-64 encoded image there isnt shown/blank + the looks of it.

![image](https://github.com/catalyst/moodle-tool_encoded/assets/42199572/a86ef8e8-58cf-4c91-a258-81bcd09ce551)

![image](https://github.com/catalyst/moodle-tool_encoded/assets/42199572/20f22a8b-bd5d-401c-bc53-063299e389ae)

Any suggestension why that could have happend?

**Comment by bwalkerl** [comment]
Thanks for the report, apologies for the delay in getting around to it. I believe this was addressed by #24 so I'll close this off.
